
name: ARTutorial

options:
  bundleIdPrefix: com.ARTutorial
  


targets:
  Hijauin:
    type: application
    platform: iOS
    

    deploymentTarget: "26.0"
        
    sources:
      - ARTutorial/

    resources:
      - ARTutorial/Assets.xcassets

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ar.tutorial

    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait

    scheme:
      testTargets: []
